### ISSUE TITLE
Outdated python version for the automation script 👀 

### ISSUE THREAD

**Issue by felipecosta09** [aws-samples/aws-modernization-with-cloud-one-workload-security#3]
The python version of the lambda automation is outdated:

https://github.com/aws-samples/aws-modernization-with-cloud-one-workload-security/blob/main/static/cft/agent-automation.yaml#L211

Upgrade to version 3.8 solve the issue and is a non-breaking change.

**Comment by JustinDPerkins** [comment]
Thank you for pointing that out. It's been updated.

**Comment by felipecosta09** [comment]
Awesome! ❤️
